Proyecto 1. Sistemas Operativos
Presentado por: JUan Camilo Chafloque, Cristobal Castrillon y Jorge Salgado

Makefile

/* Comando csortp */

gcc -o csortp csortp.c
./csortp log1000 log1000A log1000B output1000p.txt
./csortp log10K log10KA log10KB output10Kp.txt
./csortp log20K log20KA log20KB output20Kp.txt


/* Comando csorth */

gcc -o csorth csorth.c -lpthread
./csorth log1000 log1000A log1000B output1000h.txt
./csorth log10K log10KA log10KB output10Kh.txt
./csorth log20K log20KA log20KB output20Kh.txt


/* Comando csortpexec */
gcc -o csortpexec csortpexec.c
./csortpexec log1000 log1000A log1000B output1000ex.txt
./csortpexec log10K log10KA log10KB output10Kex.txt
./csortpexec log20K log20KA log20KB output20Kex.txt


